services:
  - type: web
    name: giveaway-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port 10000
    envVars:
      - key: WEB_CONCURRENCY
        value: 1
    runtime: python-3.11
