services:
  - type: web
    name: giveaway-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_SHEETS_CREDENTIALS_JSON
        sync: false
      - key: WEBHOOK_URL
        sync: false
